version: "3.3"

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      # - MINIO_SERVER_URL=http://tudominio.com:9000
    volumes:
      - ./data:/data
    command: server --console-address ":9090" /data
    restart: unless-stopped
